import { Question } from "./types";

export const questions: Question[] = [
  {
    id: 0,
    type: "multiple_choice",
    question:
      "Welk huisdier had Erik vroeger, dat hij op een gegeven moment verkocht op de rommelmarkt?",
    options: ["Cavia's", "Wandelende takken", "Een schildpad", "Goudvissen"],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 1,
    type: "multiple_choice",
    question: "Welke bijnaam kregen Eriks benen in de sportschool?",
    options: ["Luciferstokjes", "Kebabstaven", "Cocktailprikkers", "Rietjes"],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 2,
    type: "multiple_choice",
    question:
      "Marly is dol op maisvingers eten. Wat hebben Marly en Cas gemeen als het op lekkers aankomt?",
    options: [
      "Ze bakken het liever zelf",
      "Ze graaien er allebei gulzig naar",
      "Ze delen het altijd eerlijk",
      "Ze eten het nooit op feestjes",
    ],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 3,
    type: "multiple_choice",
    question:
      "Waar is Erik na het uitgaan wel eens slapend aangetroffen? (Hij is bekend als 'makkelijke slaper')",
    options: ["Op de bank", "In de tuin", "Op de badkamervloer", "In de auto"],
    correctIndex: 2,
    timeLimitSeconds: 20,
  },
  {
    id: 4,
    type: "multiple_choice",
    question: "In welke plaats woonden Cas en Erik voor het eerst samen?",
    options: ["Gouda", "Ouderkerk", "Waddinxveen", "Amstelveen"],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 5,
    type: "multiple_choice",
    question: "Hoe/waar vroeg Erik Cas ten huwelijk?",
    options: [
      "Op het strand in Portugal",
      "In een bootje in Griekenland",
      "Bovenop een berg in Oostenrijk",
      "Tijdens een stadswandeling in Parijs",
    ],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 6,
    type: "multiple_choice",
    question: "Waarmee bouwde Erik als kind het allerliefst?",
    options: [
      "Alleen met Lego",
      "Met K'nex, Duplo en zelfgebouwde hutten",
      "Met Meccano en houten blokken",
      "Alleen met kartonnen dozen",
    ],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 7,
    type: "multiple_choice",
    question: "Wat verzamelde Erik vroeger fanatiek?",
    options: ["Voetbalplaatjes", "Pokémonkaarten", "Stripboeken", "Postzegels"],
    correctIndex: 1,
    timeLimitSeconds: 20,
  },
  {
    id: 8,
    type: "multiple_choice",
    question: "Wat was het favoriete vak van Erik op school?",
    options: ["Wiskunde", "Geschiedenis", "Aardrijkskunde", "Gym"],
    correctIndex: 2,
    timeLimitSeconds: 20,
  },
  {
    id: 9,
    type: "multiple_choice",
    question:
      "Cas en Erik waren allebei op dezelfde plek voordat ze elkaar kenden. Waar?",
    options: [
      "Op een festival in Nederland",
      "Op een skivakantie in Oostenrijk",
      "Op een camping in Spanje, Platja d'Aro",
      "Op een cruise in de Middellandse Zee",
    ],
    correctIndex: 2,
    timeLimitSeconds: 20,
  },
  {
    id: 10,
    type: "multiple_choice",
    question: "Wat vergat Erik meermaals als hij op vakantie ging?",
    options: ["Zijn paspoort", "Zijn zonnebril", "Zijn schoenen", "Zijn portemonnee"],
    correctIndex: 2,
    timeLimitSeconds: 20,
  },
  {
    id: 11,
    type: "multiple_choice",
    question: "Waar (bij welke club) scoorde Erik zijn 2 belangrijkste doelpunten?",
    options: [
      "Bij Alphense Boys",
      "Bij DOSR in Roelofarendsveen",
      "Bij VVSB",
      "Bij Roda '23",
    ],
    correctIndex: 1,
    videoUrl: "/questions/vraag-14.mp4",
    videoIntro: true,
    timeLimitSeconds: 20,
  },
  {
    id: 12,
    type: "multiple_choice",
    question: "Wat bestellen Cas en Erik het liefst als ze eten laten bezorgen?",
    options: ["Pizza", "Chinees", "Sushi", "Poke bowls"],
    correctIndex: 2,
    timeLimitSeconds: 20,
  },
  {
    id: 13,
    type: "multiple_choice",
    question: "Over hoeveel trajecten is Erik verkeersleider bij ProRail?",
    options: ["Vier", "Acht", "Twee", "Zes"],
    correctIndex: 3,
    timeLimitSeconds: 20,
  },
  {
    id: 14,
    type: "multiple_choice",
    question: "Hoe heten de katten van Erik en Cas?",
    options: ["Milo & Suus", "Lilo & Guus", "Lilo & Truus", "Milo & Guus"],
    correctIndex: 0,
    imageUrl: "/questions/vraag-katten.jpg",
    timeLimitSeconds: 25,
  },
];
